### ISSUE TITLE
Feature request: Enable calling LIP connect with longer timeout

### ISSUE THREAD

**Issue by ChrisRomp** [bdraco/aiolip#2]
* Async Lutron Integration Protocol version: 1.1.4
* Python version: 3.7
* Operating System: Ubuntu 18

### Description

Need to call `async_connect` with longer timeout.

Background:  
This took quite a bit of digging, but after trying to figure out if there was a network reason for the LIP connection to not establish, I noticed that when manually connecting via telnet I would receive a prompt after a 30 second delay. That helped me find [this forum post](https://forums.lutron.com/showthread.php/3031-30-second-Telnet-Login-Delay?p=15400&viewfull=1#post15400) that indicates the Caseta is trying to connect back to the host system on TCP 113 for an `IDENT` operation, and timing out (seems the packets are being dropped and not denied - I'm using this from within Home Assistant but I'm looking into corrective options there as well).

Meanwhile, it seems the Lutron Caseta component of Home Assistant could be updated to specify a longer timeout if that becomes an option in aiolip.  I plan on opening an issue there and linking back here.

### What I Did

telnet to Caseta Pro IP

**Comment by ChrisRomp** [comment]
FYI it's SOCKET_TIMEOUT from my testing for waiting for the prompt:

E.g.: https://github.com/bdraco/aiolip/blob/master/aiolip/protocol.py#L46

The connection happens quickly, but then the delay is waiting for the prompt.

**Comment by bdraco** [comment]
> FYI it's SOCKET_TIMEOUT from my testing for waiting for the prompt:
> 
> E.g.: [https://github.com/bdraco/aiolip/blob/master/aiolip/protocol.py#L46](https://github.com/bdraco/aiolip/blob/master/aiolip/protocol.py?rgh-link-date=2021-07-28T23%3A10%3A01Z#L46)
> 
> The connection happens quickly, but then the delay is waiting for the prompt.

That makes more sense since the connection gets setup but blocks while the ident happens 👍
